export type BudgetRow = {ug:string;action:string;pi:string;nd:string;month:string;paid:number;committed:number|null;settled:number|null;budget:number|null;extra:Record<string,string>};
export type Dataset = {rows:BudgetRow[];fileName:string;updatedAt:string;currency:string;mode:'snapshot'|'monthly';reference:string;available:string[];ugAliases:Record<string,string>;skipped:number;derived?:boolean;percentBase?:'credit'|'committed'};
export const UGS:Record<string,string>={'120038':'DIRMAB','120026':'PAMA-LS','120001':'GABAER','120068':'PAMA-SP','120048':'PAME-RJ','120071':'CELOG','120049':'PAMA-GL','120090':'CABW','120036':'DECEA','120058':'DIRSA','120111':'EMAER','120136':'DIRAP','120142':'IEAv','120700':'DIREF','120106':'CENIPA','120110':'DCTA','120047':'PAMB-RJ','120624':'BAAN','120115':'COMAE','120128':'CCA-RJ','120132':'DIRENS','120032':'DTI','120130':'COMGAP','120054':'UNIFA','120035':'CTLA','120091':'CABE','120127':'CISCEA','120141':'IAE','120143':'IFI','120197':'IAOp','120283':'GECAMP','120299':'IPEV'};
export const fields=[['ug','UG responsável'],['ugName','Sigla da UG (opcional)'],['action','Código da ação'],['pi','Plano interno (PI)'],['nd','Natureza de despesa (ND)'],['month','Mês / competência'],['paid','Pagamentos realizados'],['committed','Empenhado'],['settled','Liquidado'],['budget','Dotação / crédito disponível']] as const;
export const normalize=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const aliases:Record<string,string[]>={ug:['ugresponsavelcodigo','codigougresponsavel','ugresponsavel','ugr','ug'],ugName:['ugresponsavelsigla','siglaugr','siglaug','sigla'],action:['acaoorcamentariacodigo','acaoorcamentaria','acaogoverno','codigoacao','acao'],pi:['planointernocodigo','planointerno','pi'],nd:['naturezadedespesacodigo','naturezadespesacodigo','naturezadedespesa','naturezadespesa','nd'],month:['meslancamento','mesreferencia','mes','competencia','periodo','data'],paid:['despesaspagas','despesapaga','pagamentosrealizados','valorpago','pago','pagamentos'],committed:['despesasempenhadas','despesaempenhada','empenhado','valorempenhado'],settled:['despesasliquidadas','despesaliquidada','liquidado','valorliquidado'],budget:['dotacaoatualizada','creditorecebido','creditodisponivel','creditoautorizado','dotacao','provisao']};
export function autoMap(headers:string[]){const map:Record<string,string>={};for(const [field,names] of Object.entries(aliases)){let i=headers.findIndex(h=>names.includes(normalize(h)));if(i<0)i=headers.findIndex(h=>names.some(a=>a.length>5&&normalize(h).includes(a))&&!/descricao|nome/.test(normalize(h)));map[field]=i<0?'':String(i)}return map}
export function numberValue(v:unknown):number {if(typeof v==='number'){if(!Number.isFinite(v))throw Error('Valor numérico inválido');return v}let s=String(v??'').trim();if(!s||s==='-'||s==='—')return 0;s=s.replace(/R\$|US\$|USD|BRL|EUR|€|\$|\s/g,'');const neg=s.startsWith('(')&&s.endsWith(')');if(neg)s=s.slice(1,-1);if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');if(!/^[+-]?\d+(\.\d+)?$/.test(s))throw Error('Valor inválido: '+String(v));return Number(s)*(neg?-1:1)}
export function monthValue(v:unknown,fallback:string):string {if(v===undefined||v===null||String(v).trim()==='')return fallback;let s=String(v).trim().toUpperCase();if(v instanceof Date)return v.toISOString().slice(0,7);if(typeof v==='number'&&v>30000&&v<80000)return new Date((v-25569)*86400000).toISOString().slice(0,7);let m=s.match(/^(\d{4})[-/](\d{1,2})(?:[-/]\d{1,2})?$/);if(m&&+m[2]>=1&&+m[2]<=12)return `${m[1]}-${m[2].padStart(2,'0')}`;m=s.match(/^(?:(\d{1,2})[-/])?(\d{1,2})[-/](\d{4})$/);if(m&&+m[2]>=1&&+m[2]<=12)return `${m[3]}-${m[2].padStart(2,'0')}`;const names=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];m=s.match(/([A-Z]{3})\w*\s*[-/]?\s*(\d{4})/);if(m&&names.includes(m[1]))return `${m[2]}-${String(names.indexOf(m[1])+1).padStart(2,'0')}`;if(/^\d{1,2}$/.test(s)&&+s>=1&&+s<=12)return `${fallback.slice(0,4)}-${s.padStart(2,'0')}`;throw Error('Competência não reconhecida: '+s)}
function code(v:unknown,kind:string){const s=String(v??'').trim();if(!s)return 'Não informado';if(kind==='action'){const m=s.match(/^([0-9A-Z]{4})(?:\s|[-–·]|$)/i);if(m)return m[1].toUpperCase()}if(kind==='ug'||kind==='nd'){const m=s.match(/^(\d{6})(?:\s|[-–·]|$)/);if(m)return m[1]}if(kind==='pi')return s.split(/\s+[-–·]\s+/)[0];return s}
export function parseRows(matrix:unknown[][],headerIndex:number,mapping:Record<string,string>,reference:string){if(['ug','action','pi','nd','paid'].some(f=>mapping[f]===''||mapping[f]===undefined))throw Error('Associe UG, ação, PI, ND e pagamentos.');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(reference))throw Error('Informe a competência da base.');const headers=matrix[headerIndex].map((v,i)=>String(v??'').trim()||'Coluna '+(i+1));const mapped=new Set(Object.values(mapping).filter(Boolean).map(Number));const aliasesOut:Record<string,string>={};let skipped=0;const rows:BudgetRow[]=[];for(let i=headerIndex+1;i<matrix.length;i++){const raw=matrix[i];if(!raw||raw.every(v=>v==null||String(v).trim()===''))continue;const value=(f:string)=>mapping[f]===''||mapping[f]===undefined?undefined:raw[+mapping[f]];const dims=['ug','action','pi','nd'].map(value);if(dims.some(v=>/^\s*(total|subtotal|total geral)(\b|\s)/i.test(String(v)))||dims.every(v=>v==null||String(v).trim()==='')){skipped++;continue}try{const row:BudgetRow={ug:code(value('ug'),'ug'),action:code(value('action'),'action'),pi:code(value('pi'),'pi'),nd:code(value('nd'),'nd'),month:monthValue(value('month'),reference),paid:Math.round(numberValue(value('paid'))*100)/100,committed:null,settled:null,budget:null,extra:{}};for(const f of ['committed','settled','budget'] as const)if(mapping[f]!=='')row[f]=Math.round(numberValue(value(f))*100)/100;row.settled=row.paid;const label=String(value('ugName')??'').trim();if(label&&/^[A-Za-z][A-Za-z0-9\s.-]{1,19}$/.test(label))aliasesOut[row.ug]=label;headers.forEach((h,j)=>{if(!mapped.has(j)&&raw[j]!=null&&String(raw[j]).trim())row.extra[`${h} [${j+1}]`]=String(raw[j])});rows.push(row)}catch(e){throw Error(`Linha ${i+1}: ${(e as Error).message}`)}}if(!rows.length)throw Error('Nenhum registro encontrado abaixo do cabeçalho.');if(rows.length>50000)throw Error('Limite de 50.000 registros por base.');return {rows,skipped,ugAliases:{...UGS,...aliasesOut},available:['paid','settled',...['committed','budget'].filter(f=>mapping[f]!=='')]}}
export function sum(rows:BudgetRow[],field:'paid'|'committed'|'settled'|'budget'){const values=rows.map(r=>r[field]).filter(v=>v!==null) as number[];return values.length?values.reduce((a,b)=>a+Math.round(b*100),0)/100:null}
export function periodRows(rows:BudgetRow[],month:string,mode:string,scope:string){if(scope==='period')return rows.filter(r=>r.month===month);if(mode==='snapshot')return rows.filter(r=>r.month===month);return rows.filter(r=>r.month.slice(0,4)===month.slice(0,4)&&r.month<=month)}
// TG pivot: monthly blocks across columns; each block is a complete snapshot.
export function prepareTesouro(matrix:unknown[][],percentBase:'credit'|'committed'='credit'):{matrix:unknown[][];derived:boolean;reference?:string}{
const measure=matrix.findIndex(r=>r.some(c=>normalize(c)==='creditorecebido')&&r.some(c=>normalize(c)==='pago'||normalize(c)==='percentualpago'));
if(measure<1)return {matrix,derived:false};
const dims=matrix.slice(0,measure).findLast(r=>r.some(c=>normalize(c)==='ugresponsavel')&&r.some(c=>normalize(c).startsWith('acao')));
if(!dims)return {matrix,derived:false};
const metrics=matrix[measure];
const idx=(n:string)=>dims.findIndex(c=>normalize(c).startsWith(n));
const ug=idx('ugresponsavel'),action=idx('acao'),nd=idx('naturezadespesa'),pi=idx('pi');
if([ug,action,nd,pi].some(v=>v<0))return {matrix,derived:false};
const blocks:{cr:number;ep:number;pg:number;month:string}[]=[];
for(let j=0;j<metrics.length;j++){if(normalize(metrics[j])!=='creditorecebido')continue;
let end=metrics.findIndex((v,k)=>k>j&&normalize(v)==='creditorecebido');if(end<0)end=metrics.length;
const ep=metrics.findIndex((v,k)=>k>=j&&k<end&&normalize(v)==='empenhado'),pg=metrics.findIndex((v,k)=>k>=j&&k<end&&normalize(v)==='pago');
if(ep<0||pg<0)throw Error('Bloco mensal incompleto no cabeçalho do Tesouro.');
const candidate=matrix.slice(0,measure).flatMap(r=>r.slice(j,end)).find(v=>/^(JAN|FEV|MAR|ABR|MAI|JUN|JUL|AGO|SET|OUT|NOV|DEZ)\/?\d{4}$/i.test(String(v).trim()));
if(!candidate)throw Error('Competência ausente no bloco de colunas '+(j+1)+'–'+end+'.');
blocks.push({cr:j,ep,pg,month:monthValue(candidate,'2026-01')});}
if(!blocks.length)return {matrix,derived:false};
const out:unknown[][]=[['UG Responsável','Nome UG','Ação','Descrição Ação','ND','Descrição ND','PI','Descrição PI','Mês','Crédito Recebido','Empenhado','Pagamentos Realizados','% Empenhado (original)','% Pago (original)']];
const blank=(v:unknown)=>v===undefined||v===null||String(v).trim()==='';
for(let i=measure+1;i<matrix.length;i++){const r=matrix[i];if(!/^\d{6}$/.test(String(r[ug]).trim()))continue;
for(const b of blocks){if([r[b.cr],r[b.ep],r[b.pg]].every(blank))continue;
if(blank(r[b.cr]))throw Error(`Linha ${i+1}, ${b.month}: crédito ausente.`);
const credit=numberValue(r[b.cr]);
const ratio=(v:unknown)=>String(v).trim().endsWith('%')?numberValue(String(v).trim().slice(0,-1))/100:numberValue(v);
if(credit!==0&&[r[b.ep],r[b.pg]].some(blank))throw Error(`Linha ${i+1}, ${b.month}: percentual ausente com crédito diferente de zero.`);
const committed=credit*ratio(r[b.ep]),paid=(percentBase==='credit'?credit:committed)*ratio(r[b.pg]);
out.push([r[ug],r[ug+1],r[action],r[action+1],r[nd],r[nd+1],r[pi],r[pi+1],b.month,credit,committed,paid,r[b.ep],r[b.pg]]);}}
return {matrix:out,derived:true,reference:blocks.map(b=>b.month).sort().at(-1)};}
